apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: confine-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: afsapp.azurecr.io/auth-service:IMAGE_TAG
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: RATE_LIMIT_WINDOW_MS
          value: "900000"
        - name: RATE_LIMIT_MAX_REQUESTS
          value: "100"
        - name: PORT
          value: "3001"
        - name: JWT_EXPIRE
          value: "7d"
        - name: CLIENT_URL
          value: "https://devapp.agilefacilities.com"
        - name: BCRYPT_ROUNDS
          value: "12"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: confine-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: confine-secrets
              key: JWT_SECRET
