apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  namespace: confine-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
      - name: location-service
        image: afsapp.azurecr.io/location-service:IMAGE_TAG
        ports:
        - containerPort: 5004
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5004"
        - name: FRONTEND_URL
          value: "http://client"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
        - name: WORK_ORDER_SERVICE_URL
          value: "http://workorder-service:3012"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: confine-secrets
              key: MONGODB_URI
