apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: confine-ingress
  namespace: confine-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - devapp.agilefacilities.com
    secretName: confine-tls
  rules:
  - host: devapp.agilefacilities.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client
            port:
              number: 80
